# Generated by Django 5.0.1 on 2024-02-01 05:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_xid', models.UUIDField()),
                ('status', models.CharField(choices=[('ENABLED', 'enabled'), ('DISABLED', 'disabled')], default='disabled', max_length=10)),
                ('enabled_at', models.DateTimeField(default=None, null=True)),
                ('balance', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'wallet',
                'managed': True,
            },
        ),
    ]
