# Generated by Django 5.0.1 on 2024-02-01 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'db_table': 'auth_data',
            },
        ),
    ]
